<a href="https://colab.research.google.com/github/griffinsnest/PANDAS-PYthon/blob/main/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
!pip install pandas==1.3.0

     |████████████████████████████████| 10.8 MB 6.1 MB/s 
  Attempting uninstall: pandas
    Found existing installation: pandas 1.1.5
    Uninstalling pandas-1.1.5:
      Successfully uninstalled pandas-1.1.5
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires pandas~=1.1.0; python_version >= "3.0", but you have pandas 1.3.0 which is incompatible.


In [1]:
import pandas as pd

# Reading from and write back to CSV files

df = pd.read_csv('/content/tableconvert_csv_so70jx.csv')

print(df)

df.to_csv('write-file.csv', index=False)

df2 = pd.read_csv('write-file.csv')

print(df2)

     sepal.length  sepal.width  petal.length  petal.width    variety
0             5.1          3.5           1.4          0.2     Setosa
1             4.9          3.0           1.4          0.2     Setosa
2             4.7          3.2           1.3          0.2     Setosa
3             4.6          3.1           1.5          0.2     Setosa
4             5.0          3.6           1.4          0.2     Setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

[150 rows x 5 columns]
     sepal.length  sepal.width  petal.length  petal.width    variety
0             5.1          3.5           1.4          0.2     Setosa
1         

In [3]:
import pandas as pd
import numpy as np

# Converting PANDAS to numpy and Back again


df = pd.read_csv('/content/tableconvert_csv_so70jx.csv')

df.pop('variety')

print(df2)

a = df.to_numpy()

print(a)

# b = np.delete(a, -1)

b = np.mean(a)

print(b)

df2 = pd.DataFrame(a, columns = ['sepal.length','sepal.width','petal.length', 'petal.width'])

print(df2)

df2.mean(axis = 0) 


     sepal.length  sepal.width  petal.length  petal.width    variety
0             5.1          3.5           1.4          0.2     Setosa
1             4.9          3.0           1.4          0.2     Setosa
2             4.7          3.2           1.3          0.2     Setosa
3             4.6          3.1           1.5          0.2     Setosa
4             5.0          3.6           1.4          0.2     Setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

[150 rows x 5 columns]
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0

sepal.length    5.843333
sepal.width     3.057333
petal.length    3.758000
petal.width     1.199333
dtype: float64

In [4]:
import pandas as pd

# Read and write back JSON files

df = pd.read_json('/content/tableconvert_json_f0acan-1.json')

df.to_json("new-file.json")

pd.read_json('new-file.json')

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [1]:
import pandas as pd

# Read and write to XML files

df = pd.read_xml('/content/tableconvert_xml_1dxz8d-1.xml')
df.to_xml("new_file.xml", index=False)

pd.read_xml('new_file.xml')


sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [ ]:
import pandas as pd 
import numpy as np


data = pd.read_csv('/content/tableconvert_csv_so70jx.csv')

# works data['Mathematical Passion'].var()

# works data.dtypes

# works data.head()

# works data.describes

# data.groupby('variety')['petal.length'].std()
ser1 = pd.Series(data['petal.length'])
ser2 = pd.Series(data['petal.width'])

#ser1[~ser1.isin(ser2)]

#ser_u = pd.Series(np.union1d(ser1, ser2))  # union
#ser_i = pd.Series(np.intersect1d(ser1, ser2))  # intersect
#ser_u[~ser_u.isin(ser_i)]

